name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  diff-check:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate diffs
        shell: bash
        run: ./scripts/generate-diffs.sh

      - name: Check diff validity
        shell: bash
        run: |
          git diff --exit-code || (
            echo "::error::Generated diffs are not valid - please regenerate"
            exit 1
          )

  build:
    needs: diff-check
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn -e --no-transfer-progress clean install

      - name: Check for changes
        shell: bash
        run: |
          git diff --exit-code || (
            echo "::error::Code changes detected - run 'mvn clean verify' locally"
            exit 1
          )
